cn331assignment2/cn331assignment2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registers/', include('registers.urls')),
    path('',include('users.urls')),
]

cn331assignment2/registers/urls.py
from django.urls import path

from . import views

app_name = 'registers'

urlpatterns  = [
    path('', views.index, name='index'),
    path('quota_request/', views.quota_request, name='quota_request'),
    path('quota_semester2/', views.quota_semester2, name='quota_semester2'),
    path('cancel/<str:course>', views.cancel, name='cancel'),
    path('request/<str:course>', views.request, name='request'),
    path('complete/', views.complete, name='complete'),
]

cn331assignment2/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registers/', include('registers.urls')),
]

cn331assignment2/registers/models.py
from email.policy import default
from enum import unique
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Subject(models.Model):
    subject_id = models.CharField(max_length=64, primary_key=True)
    subject_name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.subject_id} {self.subject_name}"

class Course(models.Model):
    course = models.ForeignKey(Subject, on_delete=models.CASCADE)
    semester = models.CharField(max_length=64)
    year = models.CharField(max_length=64)
    seat = models.PositiveIntegerField(default=0) 
    current_seat = models.PositiveIntegerField(default=0)
    q_status = models.CharField(max_length=64, choices=[('Available', 'Available'), ('Full', 'Full')], default="Available")
    status = models.BooleanField(default=True)
    
    class Meta:
        unique_together = ['course', 'semester', 'year']

    def __str__(self):
        return f"{self.course.subject_id} {self.semester} {self.year}"

    def is_seat_available(self):
        return self.student_apply.count() < self.seat

class Student(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    applys = models.ManyToManyField(Course, blank=True, related_name="student_apply")

    def __str__(self):
        return f"{self.student} {self.student.first_name} {self.student.last_name}"

cn331assignment2/users/models.py
from django.db import models

# Create your models here.

cn331assignment2/registers/views.py
from django.shortcuts import render
from .models import Course, Student, Subject
from django.contrib.auth.models import User
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        subjects = Course.objects.filter(status=True)
        return render(request, 'registers/index.html',{
            'subjects' : subjects 
        })

def quota_request(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        course_apply = student_info.applys.all()
        other_course = Course.objects.exclude(id__in=course_apply.values_list('id', flat=True)).filter(status=True)

        return render(request, 'registers/quota_request.html',{
            'student_info' : student_info,
            'course_apply': course_apply,
            'other_course' : other_course,
        })

def quota_semester2(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        course_apply = student_info.applys.all()
        other_course = Course.objects.exclude(id__in=course_apply.values_list('id', flat=True)).filter(status=True)

        return render(request, 'registers/quota_semester2.html',{
            'student_info' : student_info,
            'course_apply': course_apply,
            'other_course' : other_course,
        })

def complete(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        course_apply = student_info.applys.all()
            
        return render(request, 'registers/complete.html',{
            'student_info' : student_info,
            'course_apply': course_apply,
        })

def cancel(request, course):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else: 
        course = course.split(' ')
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        subject_course = Subject.objects.get(subject_id=course[0])
        cancel_course = Course.objects.filter(course=subject_course, semester=course[1], year=course[2]).first()

        student_info.applys.remove(cancel_course)
        cancel_course.current_seat = cancel_course.student_apply.count()
        if cancel_course.is_seat_available():
            cancel_course.q_status = 'Available'
        cancel_course.save()

        if cancel_course.semester == '1':
            return quota_request(request)
        else:
            return quota_semester2(request)

def request(request, course):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else: 
        course = course.split(' ')
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        subject_course = Subject.objects.get(subject_id=course[0])
        request_course = Course.objects.filter(course=subject_course, semester=course[1], year=course[2]).first()

        if request_course.is_seat_available():
            student_info.applys.add(request_course)
            request_course.current_seat = request_course.student_apply.count()
            if not request_course.is_seat_available():
                request_course.q_status = 'Full'
            request_course.save()
       
        if request_course.semester == '1':
            return quota_request(request)
        else:
            return quota_semester2(request)

cn331assignment2/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    else:
        return render(request, 'users/index.html')

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            # return HttpResponseRedirect(reverse('users:index'))
            if not user.is_superuser:
                return HttpResponseRedirect(reverse('users:index'))
            else:
                return redirect('/admin/')
        else:
            return render(request, 'users/login.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'Logged out'
    })

cn331assignment2/registers/templates/registers/complete.html
{% extends 'registers/layout.html' %}
{% block body %}

<h2 style="color:Peru;">{{student_info}}</h>

    <h2 style="color:SaddleBrown;"><u class="spelling-error"><center>Enrollment Result</center></u></h2>
    <table id="customers">
        <tr>
            <th style="font-size:125%;"><center> Course Code </center></th>
            <th style="font-size:125%;"><center> Course Name </center></th>
            <th style="font-size:125%;"><center> Semester </center></th>
            <th style="font-size:125%;"><center> Year </center></th>
            <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
            <th style="font-size:125%;"><center> Status </center></th>     
        </tr>
        {%for apply in course_apply %}
        <tr>
            <td>{{apply.course.subject_id}}</td>
            <td>{{apply.course.subject_name}}</td>
            <td>{{apply.semester}}</td>
            <td>{{apply.year}}</td>
            <td>{{apply.current_seat}} / {{apply.seat}}</td>
            <td>{{apply.q_status}}</td>     
        </tr>
        {% endfor %}
    </table>
<h2></h2>
<center>
<a href="{% url 'users:index' %}">Back to Home page</a>
</center>
{% endblock %}

cn331assignment2/registers/templates/registers/index.html
{% extends 'registers/layout.html' %}
{% block body %}

<h1 style="color:SaddleBrown;"><u class="spelling-error">Course List:</u></h1>

<h2 style="color:SaddleBrown;"><u class="spelling-error">Semester 1</u></h2>

<table id="customers">
    <tr>
        <th style="font-size:125%;"><center> Course Code </center></th>
        <th style="font-size:125%;"><center> Course Name </center></th>
        <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
        <th style="font-size:125%;"><center> Status </center></th>     
    </tr>
<ul>
    {% for subject in subjects %}
    <tr>
       {% if subject.semester == '1' %}
       <td>{{ subject.course.subject_id }}</td>
       <td>{{ subject.course.subject_name }}</td>
       <td>{{ subject.current_seat }} / {{ subject.seat }}</td>
       <td style="color:red;" >{{ subject.q_status }}</td>
       {% endif %}
    </tr>
    {% endfor %}
</ul>
</table>

<center>
<h1 style="color:IndianRed;">------------------------------------------</h1>
</center>

<h2 style="color:SaddleBrown;"><u class="spelling-error">Semester 2</u></h2>

<table id="customers">
    <tr>
        <th style="font-size:125%;"><center> Course Code </center></th>
        <th style="font-size:125%;"><center> Course Name </center></th>
        <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
        <th style="font-size:125%;"><center> Status </center></th>     
    </tr>
<ul>
    {% for subject in subjects %}
    <tr>
       {% if subject.semester == '2' %}
       <td>{{ subject.course.subject_id }}</td>
       <td>{{ subject.course.subject_name }}</td>
       <td>{{ subject.current_seat }} / {{ subject.seat }}</td>
       <td style="color:red;" >{{ subject.q_status }}</td>
       {% endif %}
    </tr>
    {% endfor %}
</ul>
</table>
<h1></h1>
<center>
<a href="{% url 'registers:quota_request' %}">Enroll Semester1</a>

<a href="{% url 'registers:quota_semester2' %}">Enroll Semester2</a>
</center>

<a href="{% url 'users:index' %}" >Back to Home page</a>

{% endblock %}

cn331assignment2/registers/templates/registers/layout.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>subjects</title>
        <style>
            h1 {text-align: center;}
            a:link, a:visited {
              background-color: #f44336;
              color: white;
              padding: 15px 25px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
            }
            
            a:hover, a:active {
              background-color: red;
            }

            table, td, th ,tr{  
                border: 1px solid #ddd;
                text-align: center;
            }
              
            table {
                border-collapse: collapse;
                width: 100%;
            }
              
            th, td {
                padding: 15px;
              }
            
            .spelling-error {
                text-decoration-line: underline;
                text-decoration-style: wavy;
                text-decoration-color: red;
            }

            .right{
                float: right;
            }

            #customers td, #customers th {
                border: 1px solid #ddd;
                padding: 8px;
              }
              
            #customers tr:nth-child(even){background-color: #F5DEB3;}
              
            #customers tr:hover {background-color: #ddd;}
              
            #customers th {
                padding-top: 12px;
                padding-bottom: 12px;
                text-align: left;
                background-color: #D2B48C;
                color: white

        </style>
    </head>
    <body style="background-color:AntiqueWhite">
        {% block body %}
        {% endblock %}
    </body>
</html>

cn331assignment2/registers/templates/registers/quota_request.html
{% extends 'registers/layout.html' %}
{% block body %}

<h1 style="color:SaddleBrown;"><u class="spelling-error">Enroll Semester1</u></h1>

<h2 style="color:Peru;">{{student_info}}</h>

    
    <h2 style="color:SaddleBrown;"><u class="spelling-error">Enrolled</u></h2>
    <table id="customers">
        <tr>
            <th style="font-size:125%;">  </th>
            <th style="font-size:125%;"><center> Course Code </center></th>
            <th style="font-size:125%;"><center> Course Name </center></th>
            <th style="font-size:125%;"><center> Semester </center></th>
            <th style="font-size:125%;"><center> Year </center></th>
            <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
            <th style="font-size:125%;"><center> Status </center></th>     
        </tr>
        {%for course in course_apply %}
        <tr>
            <td> <a href="{% url 'registers:cancel' course%}">Delete</a></td>
            <td>{{course.course.subject_id}}</td>
            <td>{{course.course.subject_name}}</td>
            <td>{{course.semester}}</td>
            <td>{{course.year}}</td>
            <td>{{course.current_seat}} / {{course.seat}}</td>
            <td style="color:red;" >{{course.q_status}}</td>     
        </tr>
        {% endfor %}
    </table>
<h1></h1>
<center>
<h1 style="color:IndianRed;">------------------------------------------</h1>
</center>
<h1></h1>
    <h2 style="color:SaddleBrown;"><u class="spelling-error">Course to Enroll</u></h2>
    <table id="customers">
        <tr>
            <th style="font-size:125%;">  </th>
            <th style="font-size:125%;"><center> Course Code </center></th>
            <th style="font-size:125%;"><center> Course Name </center></th>
            <th style="font-size:125%;"><center> Semester </center></th>
            <th style="font-size:125%;"><center> Year </center></th>
            <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
            <th style="font-size:125%;"><center> Status </center></th>   
        </tr>
        {%for course in other_course %}
        <tr>
            {% if course.semester == '1' %}
                <td> <a href="{% url 'registers:request' course%}">Select</a></td>
                <td>{{course.course.subject_id}}</td>
                <td>{{course.course.subject_name}}</td>
                <td>{{course.semester}}</td>
                <td>{{course.year}}</td>
                <td>{{course.current_seat}} / {{course.seat}}</td>
                <td style="color:red;" >{{course.q_status}}</td>     
            {% endif %}
        </tr>
        {% endfor %}
    </table>
<h1></h1>

<center>
<a href="{% url 'registers:complete' %}"> Confirm </a>
</center>


<a href="{% url 'users:index' %}" >Back to Home page</a>


{% endblock %}

cn331assignment2/registers/templates/registers/quota_semester2.html
{% extends 'registers/layout.html' %}
{% block body %}

<h1 style="color:SaddleBrown;"><u class="spelling-error">Enroll Semester2</u></h1>

<h2 style="color:Peru;">{{student_info}}</h>

    
    <h2 style="color:SaddleBrown;"><u class="spelling-error">Enrolled</u></h2>
    <table id="customers">
        <tr>
            <th style="font-size:125%;">  </th>
            <th style="font-size:125%;"><center> Course Code </center></th>
            <th style="font-size:125%;"><center> Course Name </center></th>
            <th style="font-size:125%;"><center> Semester </center></th>
            <th style="font-size:125%;"><center> Year </center></th>
            <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
            <th style="font-size:125%;"><center> Status </center></th>    
        </tr>
        {%for course in course_apply %}
        <tr>
            <td> <a href="{% url 'registers:cancel' course%}">Delete</a></td>
            <td>{{course.course.subject_id}}</td>
            <td>{{course.course.subject_name}}</td>
            <td>{{course.semester}}</td>
            <td>{{course.year}}</td>
            <td>{{course.current_seat}} / {{course.seat}}</td>
            <td style="color:red;" >{{course.q_status}}</td>     
        </tr>
        {% endfor %}
    </table>
<h1></h1>
<center>
<h1 style="color:IndianRed;">------------------------------------------</h1>
</center>
<h1></h1>
    <h2 style="color:SaddleBrown;"><u class="spelling-error">Course to Enroll</u></h2>
    <table id="customers">
        <tr>
            <th style="font-size:125%;">  </th>
            <th style="font-size:125%;"><center> Course Code </center></th>
            <th style="font-size:125%;"><center> Course Name </center></th>
            <th style="font-size:125%;"><center> Semester </center></th>
            <th style="font-size:125%;"><center> Year </center></th>
            <th style="font-size:125%;"><center> Quantity(remain/limit) </center></th>
            <th style="font-size:125%;"><center> Status </center></th>    
        </tr>
        {%for course in other_course %}
        <tr>
            {% if course.semester == '2' %}
                <td> <a href="{% url 'registers:request' course%}">Select</a></td>
                <td>{{course.course.subject_id}}</td>
                <td>{{course.course.subject_name}}</td>
                <td>{{course.semester}}</td>
                <td>{{course.year}}</td>
                <td>{{course.current_seat}} / {{course.seat}}</td>
                <td style="color:red;" >{{course.q_status}}</td>     
            {% endif %}
        </tr>
        {% endfor %}
    </table>
<h1></h1>

<center>
<a href="{% url 'registers:complete' %}"> Confirm </a>
</center>


<a href="{% url 'users:index' %}" >Back to Home page</a>


{% endblock %}

cn331assignment2/users/templates/users/index.html
{% extends 'users/layout.html' %}
{% block body %}
<h1 style="font-size:300%;"><u class="spelling-error">Welcome, {{ request.user.first_name }}</u></h1>

<h2 style="font-size:150%;">Username: {{ request.user.username }}</h2>
<h2 style="font-size:150%;">Email: {{ request.user.email }}</h2>

<a href="{% url 'registers:index' %}">View Course List</a>
<h2></h2>
<a href="{% url 'registers:quota_request' %}">Enroll Semester1</a>
   
<a href="{% url 'registers:quota_semester2' %}">Enroll Semester2</a>
<h2></h2>  
<a href="{% url 'users:logout' %}">Log out</a>
{% endblock %}

cn331assignment2/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Users</title>
        <style>
          h1 {color:SaddleBrown;}

          h2 {color:Peru;}

            a:link, a:visited {
              background-color: #f44336;
              color: white;
              padding: 15px 25px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
            }
            
            a:hover, a:active {
              background-color: red;
            }

            .spelling-error {
              text-decoration-line: underline;
              text-decoration-style: wavy;
              text-decoration-color: red;
          }

          .button {
            background-color: SandyBrown;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
          }

            </style>
          
    </head>
    <body style="background-color:AntiqueWhite">
      <center>
        {% block body %}
        {% endblock %}
      </center>
    </body>
</html>

cn331assignment2/users/templates/users/login.html
{% extends 'users/layout.html' %}
{% block body %}
<h1 style="font-size:300%;"><u class="spelling-error">Login</u></h1>
{% if message %}
    <div style="color:red">{{ message }}</div>
{% endif %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <h1></h1>
    <center>
    <button class="button">Login</button>
    </center>
</form>
{% endblock %}